name = "btc-oracle"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
PAYMENT_ADDRESS = "SPKH9AWG0ENZ87J1X0PBD4HETP22G8W22AFNVF8K"
CONTRACT_ADDRESS = "SP_DEPLOYED_CONTRACT_ADDRESS"
HIRO_API = "https://api.hiro.so"

[[kv_namespaces]]
binding = "CACHE"
id = "45bb82d6ebd44b7ea02cc5b7bb996ac8"
